### ISSUE TITLE
Demo web JTR with federalist

### ISSUE THREAD

**Issue by thebestsophist** [18F/dtmo-pa#36]
Not sure if we want to do this, but it might be a quick win.

Perhaps use the [basic report template](https://github.com/adborden/federalist-basic-report-template)

**Comment by eddietejeda** [comment]
Do you have screenshot of how this looks?

**Comment by thebestsophist** [comment]
Repo here: @18f/dtmo-jtr-prototype
URL: https://federalist-proxy.app.cloud.gov/site/18f/dtmo-jtr-prototype/
